site_name: pg-structure 3.1.1
theme: readthedocs
pages:
  - Home: index.md
  - Concepts: concepts.md
  - Examples: examples.md
  - History: history.md
  - License: license.md
  - 'Test & Coverage Report': report.md
  - API:
      - Column: api/Column.md
      - Constraint: api/Constraint.md
      - Db: api/Db.md
      - Index: api/Index.md
      - M2M Relation: api/M2MRelation.md
      - M2O Relation: api/M2ORelation.md
      - Map: api/Map.md
      - O2M Relation: api/O2MRelation.md
      - pgStructure: api/PgStructure.md
      - Schema: api/Schema.md
      - Table: api/Table.md
site_url: 'http://www.pg-structure.com'
repo_url: 'https://github.com/ozum/pg-structure.git'
site_description: Get PostgreSQL database structure as a detailed JS Object.
site_author: Özüm Eldoğan
google_analytics:
  - UA-45732546-4
  - auto
docs_dir: docs
copyright: © Özüm Eldoğan
